# Generated by Django 5.2.8 on 2026-08-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='place',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='course',
            field=models.CharField(blank=True, choices=[('Python', 'Python'), ('Java', 'Java'), ('Web Development', 'Web Development'), ('Django', 'Django'), ('Data Structures', 'Data Structures'), ('C++', 'C++'), ('JavaScript', 'JavaScript'), ('Machine Learning', 'Machine Learning')], max_length=50),
        ),
    ]
