# Generated by Django 5.2.8 on 2026-08-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_userprofile_age_userprofile_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='degree',
            field=models.CharField(blank=True, choices=[('BCA', 'BCA'), ('BSc', 'BSc'), ('BCom', 'BCom'), ('BE/BTech', 'BE/BTech'), ('MCA', 'MCA'), ('MSc', 'MSc')], max_length=50),
        ),
    ]
