# Generated by Django 5.2.8 on 2026-09-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_pagevisit_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='device_info',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='referrer',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
