# Generated by Django 5.2.8 on 2026-09-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_pagevisit_device_info_pagevisit_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('travel', 'Travel'), ('tech', 'Tech'), ('personal', 'Personal'), ('food', 'Food'), ('lifestyle', 'Lifestyle'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
